name = "TYMTYM"
main = "src/index.js"
compatibility_date = "2025-01-08"

[vars]
BOT_TOKEN = "7720361034:AAF9y-kaCN8juLbf1xDSyzKFE2ddlrbS6Mk"
BOT_USERNAME = "Tym10k_Bot"
EMOJI_LIST = "👍❤🔥🥰👏😁🎉🤩🙏👌🕊😍🐳😇😎🙂‍↔️😗😇😕🥳🧐🤨🥰🥲🤩😝🥳😢😢🥶🥵🤬😱😤😍🤣🤣😂😃😀❤‍🔥💯⚡🏆"
RANDOM_LEVEL = "1"
RESTRICTED_CHATS = ","
