name = "telegram-bot-worker"
type = "javascript"  # You can change this based on your worker
account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
compatibility_date = "2023-09-06"

[env.production]
workers_dev = true
