name: Deploy Telegram Bot to Cloudflare Workers

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Wrangler CLI for Cloudflare Workers
      - name: Install Wrangler
        run: npm install -g wrangler

      # Authenticate Wrangler with Cloudflare using API token from GitHub secrets
      - name: Authenticate Wrangler
        run: wrangler config --api-token ${{ secrets.CLOUDFLARE_API_TOKEN }}

      # Publish to Cloudflare Workers
      - name: Deploy to Cloudflare
        run: wrangler publish

      # Show deployment result
      - name: Show deployment
        run: wrangler tail
