name: Deploy to Cloudflare Workers

on: 
  workflow_dispatch:
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            BOT_TOKEN
            BOT_USERNAME
            EMOJI_LIST
            RANDOM_LEVEL
            RESTRICTED_CHATS
        env:
          BOT_TOKEN: ${{ 7539216226:AAEG4A26rdA650MFzx_kx2gNj3ukcswUoRU }}
          BOT_USERNAME: ${{ @DOGRAT1O1BOT }}
          EMOJI_LIST: ${{ 👍❤🙏😍👏 }}
          RANDOM_LEVEL: ${{ 0 }}
          RESTRICTED_CHATS: ${{ secrets.RESTRICTED_CHATS }}
